# on:
#   push:
#     branches: 
#       - develop
#       - staging
#       - master

# jobs: 
#   test_apps:
#     name: Testing React App
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Running Web Test
#         run: 
#       - name: Running Module Test
#         run: 
#       - name: Running Common Test
#         run: 

#   test_apis:
#     name: Testing Dev API